import { useEffect, useState } from 'react';
import { omit } from 'lodash';
import {
  Button,
  Col,
  Popconfirm,
  Row,
  Space,
  Spin,
  Typography,
  Alert,
} from 'antd';
import type { ColumnsType } from 'antd/es/table';
import DeleteOutlined from '@ant-design/icons/DeleteOutlined';
import EditOutlined from '@ant-design/icons/EditOutlined';
import PlusOutlined from '@ant-design/icons/PlusOutlined';
import ModelRelationSelectionTable, {
  RelationsDataType,
} from '@/components/table/ModelRelationSelectionTable';
import { getJoinTypeText } from '@/utils/data';
import useModalAction from '@/hooks/useModalAction';
import RelationModal, {
  RelationFieldValue,
  RelationFormValues,
} from '@/components/modals/RelationModal';
import { convertFormValuesToIdentifier } from '@/hooks/useCombineFieldOptions';

const { Title, Text } = Typography;

// for omit keys
const relationKeys = ['name', 'isAutoGenerated'];

export interface SelectedRecommendRelations {
  [modelName: string]: RelationsDataType[];
}

interface Props {
  fetching: boolean;
  recommendRelations: SelectedRecommendRelations;
  recommendNameMapping: Record<string, string>;
  onNext: (data: { relations: SelectedRecommendRelations }) => void;
  onBack: () => void;
  onSkip: () => void;
  submitting: boolean;
}

interface EditableRelationTableProps {
  index: number;
  modelName: string;
  onSetRelation: (payload: {
    modelName: string;
    defaultValue?: RelationsDataType;
  }) => void;
  onDeleteRow: (modelName: string, selectedRelation: RelationsDataType) => void;
  relations: RelationsDataType[];
  recommendNameMapping: Record<string, string>;
}

function EditableRelationTable(props: EditableRelationTableProps) {
  const {
    index,
    modelName,
    onSetRelation,
    onDeleteRow,
    relations,
    recommendNameMapping,
  } = props;

  const columns: ColumnsType<RelationsDataType> = [
    {
      title: '来源字段',
      dataIndex: 'fromField',
      key: 'fromField',
      render: (fromField) => `${fromField.modelName}.${fromField.fieldName}`,
      width: '35%',
    },
    {
      title: '目标字段',
      dataIndex: 'toField',
      key: 'toField',
      render: (toField) => `${toField.modelName}.${toField.fieldName}`,
      width: '35%',
    },
    {
      title: '关系类型',
      dataIndex: 'type',
      key: 'type',
      render: (type, relation) => (
        <>
          {getJoinTypeText(type)}
          {relation.isAutoGenerated && (
            <Text className="pl-1" type="secondary">
              （自动生成）
            </Text>
          )}
        </>
      ),
      width: '30%',
    },
    {
      title: '',
      key: 'action',
      width: 48,
      align: 'center',
      render: (_, record) => (
        <Space size={[16, 0]}>
          <EditOutlined
            onClick={() =>
              onSetRelation({
                modelName,
                defaultValue: record,
              })
            }
          />
          <Popconfirm
            title="确认删除吗？"
            okText="删除"
            okButtonProps={{ danger: true }}
            onConfirm={() => onDeleteRow(modelName, record)}
          >
            <DeleteOutlined />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div className="mt-6">
      <ModelRelationSelectionTable
        columns={columns}
        dataSource={relations}
        tableTitle={recommendNameMapping[modelName]}
        extra={(onCollapseOpen) => (
          <Button
            onClick={(event) => {
              onSetRelation({ modelName });
              onCollapseOpen(event, recommendNameMapping[modelName]);
            }}
            size="small"
            title="新增关系"
          >
            <PlusOutlined />
            新增
          </Button>
        )}
        rowKey={(record: RelationsDataType) =>
          `${modelName}-${record.fromField.fieldName}-${record.toField.modelName}-${record.toField.fieldName}-${index}`
        }
      />
    </div>
  );
}

export default function DefineRelations(props: Props) {
  const {
    fetching,
    recommendRelations,
    recommendNameMapping,
    onBack,
    onNext,
    onSkip,
    submitting,
  } = props;

  const [relations, setRelations] =
    useState<SelectedRecommendRelations>(recommendRelations);

  const [selectedRelation, setSelectedRelation] = useState<{
    modelName: string;
    defaultValue?: RelationsDataType;
  }>(null);

  const [showNoRecommendationAlert, setShowNoRecommendationAlert] =
    useState<boolean>(false);

  useEffect(() => {
    setRelations(recommendRelations);

    const recommendRelationsValues = Object.values(recommendRelations);
    if (recommendRelationsValues.length === 0) return;

    const allEmpty = recommendRelationsValues.every(
      (value) => value.length === 0,
    );
    setShowNoRecommendationAlert(allEmpty);
  }, [recommendRelations]);

  const relationModal = useModalAction();

  // check is the relation is auto-generated or not
  const isRecommendRelation = (
    modelName: string,
    relation: RelationsDataType,
  ) => {
    const isOriginalRelation = (recommendRelations[modelName] || []).find(
      (originalRelation) =>
        JSON.stringify(omit(originalRelation, relationKeys)) ===
        JSON.stringify(omit(relation, relationKeys)),
    );

    return isOriginalRelation?.isAutoGenerated || false;
  };

  const onAddRelation = (relationFormValues: RelationFormValues) => {
    const relation = convertFormValuesToIdentifier(relationFormValues);
    const modelName = relation.fromField.modelName;
    const isAutoGenerated = isRecommendRelation(modelName, relation);
    const newRelations = {
      ...relations,
      [modelName]: [
        ...(relations[modelName] || []),
        { ...relation, isAutoGenerated },
      ],
    };
    setRelations(newRelations);
  };

  const onCloseModal = () => {
    setSelectedRelation(null);
    relationModal.closeModal();
  };

  const onDeleteRow = (
    modelName: string,
    selectedRelation: RelationsDataType,
  ) => {
    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].filter(
        (relation) =>
          JSON.stringify(relation) !== JSON.stringify(selectedRelation),
      ),
    };
    setRelations(newRelations);
  };

  const onSetRelation = (payload: {
    modelName: string;
    defaultValue?: RelationsDataType;
  }) => {
    setSelectedRelation(payload);
    relationModal.openModal();
  };

  const onUpdateRelation = (
    modelName: string,
    originalRelationValue: RelationsDataType,
    newRelationValue: RelationFormValues,
  ) => {
    const newRelation = convertFormValuesToIdentifier(newRelationValue);
    const isAutoGenerated = isRecommendRelation(modelName, newRelation);
    const newRelations = {
      ...relations,
      [modelName]: relations[modelName].map((relation) => {
        if (
          JSON.stringify(relation) === JSON.stringify(originalRelationValue)
        ) {
          return { ...newRelation, isAutoGenerated };
        }
        return relation;
      }),
    };

    setRelations(newRelations);
  };

  const submit = () => {
    onNext && onNext({ relations });
  };

  return (
    <div>
      <Title level={1} className="mb-3">
        定义关系
      </Title>
      <Text>
        你可以在已选数据表之间创建关系。系统会基于数据源中的主键和外键提供推荐关系，随后这些关系会被加入数据模型。
      </Text>
      {showNoRecommendationAlert && (
        <Alert
          message="没有推荐关系"
          description="由于未检测到主键或外键，系统暂时无法推荐关系。"
          type="info"
          showIcon
          className="my-6"
        />
      )}
      <div className="my-6 text-center">
        {Object.entries(relations).map(
          ([modelReferenceName, relations = []], index) => (
            <EditableRelationTable
              key={`${modelReferenceName}-${relations.length}`}
              index={index}
              modelName={modelReferenceName}
              relations={relations}
              onSetRelation={onSetRelation}
              onDeleteRow={onDeleteRow}
              recommendNameMapping={recommendNameMapping}
            />
          ),
        )}
        <Spin spinning={fetching} tip="加载中..." className="my-15" />
      </div>
      <Row gutter={16} className="pt-6">
        <Col span={12}>
          <Button onClick={onBack} size="large" className="adm-onboarding-btn">
            上一步
          </Button>
        </Col>
        <Col className="text-right" span={12}>
          <Button
            className="mr-4 gray-7 adm-onboarding-btn"
            type="text"
            size="large"
            onClick={onSkip}
            disabled={submitting}
            data-ph-capture="true"
            data-ph-capture-attribute-name="cta_skip_define_relationship"
          >
            跳过此步骤
          </Button>
          <Button
            type="primary"
            size="large"
            onClick={submit}
            className="adm-onboarding-btn"
            loading={submitting}
            disabled={fetching}
            data-ph-capture="true"
            data-ph-capture-attribute-name="cta_finish_define_relationship"
          >
            完成
          </Button>
        </Col>
      </Row>
      <RelationModal
        {...relationModal.state}
        model={selectedRelation?.modelName}
        onSubmit={async (values) => {
          if (selectedRelation?.defaultValue) {
            onUpdateRelation(
              selectedRelation.modelName,
              selectedRelation.defaultValue,
              values,
            );
          } else {
            onAddRelation(values);
          }
          setSelectedRelation(null);
        }}
        onClose={onCloseModal}
        defaultValue={
          selectedRelation?.defaultValue
            ? (omit(
                selectedRelation.defaultValue,
                relationKeys,
              ) as RelationFieldValue)
            : undefined
        }
        relations={relations}
        isRecommendMode={Boolean(selectedRelation?.defaultValue)}
      />
    </div>
  );
}
